#!/bin/bash


###############################################################################
# Start ps1-k8s
###############################################################################


build_ps1() 
{

    # local bold="\[$(tput bold)\]"
    # local cyan="\[\e[0;36m\]"
    # local  gray="\[\e[1;30m"
    local  ltPurple="\[\e[0;35m"
    local  blue="\[\e[0;34m\]"
    local  yellow="\[\e[0;33m\]"
    local  endColor="\e[0m\]"

    # local directory='\w'
    # local readonly host='\h'
    # local readonly user='\u'
    local  namespace
    local  directory
    local  cluster

    directory=$(pwd | sed "s|^$HOME|~|")
    # ctx=$(kubectl config current-context) 2> /dev/null;if [ $? -eq 0 ]; then echo $CTX;fi
    ctx="$(yq .current-context ~/.kube/config)"

    if [ "$ctx" == "null" ]; then
      # make prompt look like <:-) by adding a nose and hat
      namespace="-"  # nose
      cluster="<"    # hat
    else
      namespace="$(kubectl config view | kx="$ctx" yq '.contexts[] | select(.name ==env(kx)) | select(.context.namespace != null) | .context.namespace' -)"
      cluster="$(kubectl config current-context)"
    fi

    local prompt=""
    # prompt="${user}@"
    # prompt="${prompt}${bold}$(colorize ${host}):"
    # prompt="${prompt}$(colorize $directory $gray)"
    # prompt="${prompt}${term_reset}"
    
    # prompt="(${blue}${cluster}${endColor}:${yellow}${namespace}${endColor}) ${ltPurple}${directory}${endColor}$ "
    prompt="(${cluster}:${namespace}) ${directory}$ "

    # echo -n "${prompt}"
    PS1="${prompt}"

}

# export PS1='$(build_ps1)'
export PROMPT_COMMAND=build_ps1


###############################################################################
# End ps1-k8s
###############################################################################



